remove gcc support for sphng recipe
gcc support would require a modification to the code.

```
densityiterate_gradh_MPI.F:2028:22:

 2028 |  29               IF (ifound.EQ.0) THEN
      |                      1
Error: Operands of comparison operator ".eq." at (1) are LOGICAL(4)/INTEGER(4)
```

We shouldn't be modifying source for the benchmarks, especially
considering that the source code repos are not the official ones from
the PIs. I recommend any necessary portability changes should be added
to the current working versions of the codes (where the changes may have
already been made anyway).